#
# Copyright (C) 2024 nosignals
#
name: ULO Autobuilder

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'Kernel Version (ex. 6.6.6, 6.1.31-localversion)'
        required: true
        default: '6.6.6'
        type: string
      devices:
        description: "Devices"
        required: true
        default: "s905x"
        type: choice
        options:
          - s905x
          - s905x2
          - s905x3
          - s905x4
          - h6
          - h618
          - rk3566
          - rk3588
      rootfs_size:
        description: "ROOTFS Size, min 640 (756, 1024, 2048, etc)"
        required: true
        default: '1024'
        type: string
jobs: 
  build_ipk:
    permissions:
      contents: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    steps:
      
      - name: Cleanup and Installing Prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E apt-get update
          sudo -E apt-get -y install lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
                    
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
          
      - name: Building OpenWrt
        run: |
          sudo ./ulo -k ${{ inputs.kernel }} -m ${{ inputs.devices }} -s ${{ inputs.rootfs_size }}
          
      - name: Creating Package Artifact
        run: |
          mkdir -p ./artifact
          cp -rf ./out/${{ inputs.devices }}/* ./artifact/
          
      - name: Delivering Package
        uses: actions/upload-artifact@v2
        with:
          name: openwrt_package
          path: ./artifact/*

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/*
          tag: ${{ inputs.devices }}
          file_glob: true
          body: |
            ##  OpenWRT Release
            - Devices type : ${{ inputs.devices }}
            - Kernel version : ${{ inputs.kernel }}
            - ROOTFS Size : ${{ inputs.rootfs_size }}
